#+TITLE: PlantUML Layer
#+CATEGORY: diagram
#+PROPERTY: header-args:emacs-lisp :tangle yes
#+PROPERTY: header-args:sh :tangle setup.sh

* Description
Provides syntax highlighting, autocompletion, previewing, and syntax checking
for UML and technical diagrams. Supports standalone diagram files (.puml,
.plantuml, .pu, .wsd, .iuml) as well as inline PlantUML code blocks inside
Org-mode documents.

* Emacs Configuration
** PlantUML Mode
[[https://plantuml.com/][PlantUML]] is a tool for creating UML diagrams from a simple text description. The
~plantuml-mode~ package provides syntax highlighting, autocompletion, and
preview capabilities for PlantUML diagrams within Emacs.

#+begin_src emacs-lisp
(defvar org-src-lang-modes)
(declare-function plantuml-completion-at-point-function "plantuml")

(defun cfg-plantuml/preserve-point (orig-fun &rest args)
  "Preserve point while PlantUML calculates completion bounds.
ORIG-FUN is the advised function.
ARGS contains the advised function's arguments."
  (save-excursion
    (apply orig-fun args)))

(use-package plantuml-mode
  :mode (("\\.wsd\\'" . plantuml-mode)
         ("\\.pu\\'" . plantuml-mode)
         ("\\.puml\\'" . plantuml-mode)
         ("\\.plantuml\\'" . plantuml-mode)
         ("\\.iuml\\'" . plantuml-mode))
  :custom
  (plantuml-jar-path (expand-file-name "~/.emacs.d/plantuml/plantuml.jar"))
  (plantuml-default-exec-mode 'jar)
  (plantuml-output-type "svg")
  (plantuml-indent-level 2)
  :config
  ;; `plantuml-completion-at-point-function' moves point while calculating
  ;; completion bounds. A CAPF must leave point unchanged after being queried.
  (advice-add 'plantuml-completion-at-point-function
              :around
              #'cfg-plantuml/preserve-point)
  ;; Replace PlantUML's obsolete inserter (which inserts a unique match
  ;; immediatelly and is disruptive with Corfu's automatic completion) with
  ;; a proper CAPF. It returns the completion table, allowing Corfu to filter
  ;; and display matching candidates without inserting them automatically.
  (add-hook 'plantuml-mode-hook
            (lambda ()
              (setq-local completion-at-point-functions
                          (list #'plantuml-completion-at-point-function))))
  ;; Disable LSP when it is automatically enabled on `prog-mode':
  (add-hook 'cfg-lsp/deferred-start-predicate-functions
            (lambda () (not (derived-mode-p 'plantuml-mode))))
  ;; Trigger corfu completion on single character:
  (setf (alist-get 'plantuml-mode cfg-completion/corfu-mode-policies)
        '(:auto-prefix 1))
  ;; Enable PlantUML integration with org-mode
  (with-eval-after-load 'org
    (add-to-list 'org-src-lang-modes '("plantuml" . plantuml))))
#+end_src

** PlantUML Flycheck
#+begin_src emacs-lisp
(use-package flycheck-plantuml
  :after flycheck
  :config
  (flycheck-plantuml-setup))
#+end_src

* Keybindings
Registers keybindings for previewing and editing diagrams.

#+begin_src emacs-lisp
(declare-function plantuml-preview "plantuml-mode")
(cfg-keys/mode-leader-def plantuml-mode
  "C-c"   #'plantuml-preview
  "m"     '(:ignore t :which-key "major-mode")
  "m p"   #'plantuml-preview)
#+end_src

* System Setup
To use ~plantuml-mode~, you need to have PlantUML installed. Below we download
the PlantUML JAR file to =~/.emacs.d/plantuml/plantuml.jar=.

#+begin_src sh
# Update PlantUML version as needed:
PLANTUML_VERSION="1.2026.6"
PLANTUML_DIR="$HOME/.emacs.d/plantuml"

is_installed__lang__diagrams__plantuml() {
  [ -f "$HOME/.emacs.d/plantuml/plantuml.jar" ]
}

install__lang__diagrams__plantuml() {
  local PLANTUML_JAR="$PLANTUML_DIR/plantuml.jar"
  local PLANTUML_URL="https://github.com/plantuml/plantuml/releases/download/v${PLANTUML_VERSION}/plantuml-${PLANTUML_VERSION}.jar"

  if [ -f "$PLANTUML_JAR" ]; then
    log_skip "PlantUML" "EXISTS"
  else
    run_task "Downloading PlantUML" "mkdir -p $PLANTUML_DIR && curl -L $PLANTUML_URL -o $PLANTUML_JAR"
  fi
}

uninstall__lang__diagrams__plantuml() {
  run_task "Removing PlantUML" "rm -Rf $PLANTUML_DIR"
}

register_action "Lang" "Diagrams" "Install PlantUML" "-lang--diagrams--plantuml" "standalone"
#+end_src
